-- Autogenerated by generate_sql.go
CREATE TABLE tests (
	id                  serial      PRIMARY KEY,
	test_id             uuid        NOT NULL,
	created_at          timestamp   NOT NULL,
	updated_at          timestamp   NOT NULL,
	client_ip           inet        NOT NULL,
	client_version      text        NOT NULL,
	flash_version       text        NOT NULL,
	user_agent          text        NOT NULL,
	user_comment        text        NOT NULL,
	has_failed          boolean     NOT NULL,
	is_mitm             boolean     NOT NULL,
	is_pending          boolean     NOT NULL,
	UNIQUE (test_id)
);
CREATE TABLE subtests (
	id                  serial      PRIMARY KEY,
	test_id             integer     NOT NULL REFERENCES tests ON DELETE CASCADE,
	number              integer     NOT NULL,
	max_tls_version     integer     NOT NULL,
	is_ipv6             boolean     NOT NULL,
	has_failed          boolean     NOT NULL,
	is_mitm             boolean     NOT NULL,
	UNIQUE (test_id, number)
);
CREATE TABLE client_captures (
	id                  serial      PRIMARY KEY,
	subtest_id          integer     NOT NULL REFERENCES subtests ON DELETE CASCADE,
	created_at          timestamp   NOT NULL,
	begin_time          timestamp   NOT NULL,
	end_time            timestamp   NOT NULL,
	actual_tls_version  integer     NOT NULL,
	frames              jsonb       NOT NULL,
	key_log             text        NOT NULL,
	has_failed          boolean     NOT NULL,
	UNIQUE (subtest_id)
);
CREATE TABLE server_captures (
	id                  serial      PRIMARY KEY,
	subtest_id          integer     NOT NULL REFERENCES subtests ON DELETE CASCADE,
	created_at          timestamp   NOT NULL,
	begin_time          timestamp   NOT NULL,
	end_time            timestamp   NOT NULL,
	actual_tls_version  integer     NOT NULL,
	frames              jsonb       NOT NULL,
	key_log             text        NOT NULL,
	has_failed          boolean     NOT NULL,
	client_ip           inet        NOT NULL,
	server_ip           inet        NOT NULL,
	UNIQUE (subtest_id)
);
